name: Node.js CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 8080:8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start Docker Compose
        run: docker-compose -f docker-compose.yml up --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 30  # Wait for a few seconds to ensure services are up
        continue-on-error: true

      - name: Verify Docker Compose status
        run: docker-compose ps
        
      - name: Run Cucumber tests
        run: docker-compose up test-runner
        continue-on-error: true

      - name: Display logs for debugging (if needed)
        if: failure()
        run: docker-compose logs

      - name: Clean up Docker Compose
        if: always()
        run: docker-compose down

      - name: Post test summary
        if: failure()
        run: echo "Cucumber tests failed" && exit 1
